### ISSUE TITLE
Retrofit get api

### ISSUE THREAD

**Issue by ThitaCharon** [boredomdenied/BakingApp#5]
<img width="1252" alt="screen shot 2018-07-22 at 1 07 24 am" src="https://user-images.githubusercontent.com/25854219/43042439-b4c8ff4c-8d4b-11e8-8f2c-a6a3a42ec177.png">

The issue on Retrofit get respond. All class in Network look good. 
The problem is in Mainactivity, so you have to change something.
Create variable List<Recipe> mRecipe;
Then in line 46 mRecipe = respond.body();
and then using List<Recipe> mRecipe pass as a parameter through method generateDatalist.

**Comment by boredomdenied** [comment]
I have successfully returned the data now :) thank you :+1:
